import Footer from "@/components/Footer";

type Section = { heading: string; body: string | string[] };

const sections: Section[] = [
  {
    heading: "Acceptance of Terms",
    body: "By accessing or using Natural-Disaster.io (“the platform”, “the service”), you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must discontinue use of the service immediately.",
  },
  {
    heading: "Nature of the Service",
    body: [
      "Natural-Disaster.io is a demonstration and research platform. It aggregates publicly available data from third-party sources including GDACS, USGS, ReliefWeb, and NASA FIRMS, and uses AI language models to synthesise responses.",
      "All information provided is for informational and demonstrative purposes only.",
      "We do not guarantee the accuracy, completeness, timeliness, or reliability of any information displayed on this platform.",
      "The platform is not an official emergency service, government agency, or humanitarian organisation.",
    ],
  },
  {
    heading: "Critical Safety Notice",
    body: "DO NOT use this platform to make life-safety decisions, evacuation plans, emergency response choices, or any decision where inaccurate information could cause harm. For emergencies, contact your local emergency services (911, 112, or your country's equivalent) and official civil protection authorities.",
  },
  {
    heading: "Disclaimer of Liability",
    body: [
      "To the fullest extent permitted by applicable law, the developer (Sankalp Sandeep Indish) shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use this service.",
      "This includes, but is not limited to, damages resulting from errors or omissions in the AI-generated content, interruptions to the service, data inaccuracies from third-party feeds, or reliance on any information provided by the platform.",
    ],
  },
  {
    heading: "Third-Party Data Sources",
    body: [
      "The platform relies on data from GDACS (EC Joint Research Centre), ReliefWeb (UN OCHA), USGS, NASA FIRMS, and other public APIs. We are not responsible for the content, accuracy, or availability of these external sources.",
      "Data from these sources is subject to their own terms of use and licensing. Refer to each provider's website for their respective policies.",
      "GDACS data is used under the terms available at gdacs.org. ReliefWeb data is used under Creative Commons Attribution licensing as described at reliefweb.int/terms-conditions.",
    ],
  },
  {
    heading: "Intellectual Property",
    body: "The platform's source code, design system, and original written content are the intellectual property of Sankalp Sandeep Indish. The underlying data displayed belongs to its respective providers. You may not reproduce, distribute, or create derivative works from the platform's proprietary components without explicit written permission.",
  },
  {
    heading: "AI-Generated Content",
    body: [
      "Responses generated by the AI agent are produced by a large language model (Llama 3.3 70B via Groq). AI outputs may be incomplete, outdated, or incorrect.",
      "AI-generated summaries should always be verified against the original source data before any consequential action is taken.",
      "The platform includes safety guardrails that prevent the AI from providing evacuation routes or life-safety instructions. These guardrails are not infallible.",
    ],
  },
  {
    heading: "Permitted Use",
    body: [
      "You may use this platform for personal research, educational purposes, and demonstration of AI capabilities.",
      "You may not use this platform in any way that violates applicable laws, infringes on third-party rights, or attempts to circumvent the platform's safety guardrails.",
      "Automated or bulk querying of the platform without prior written consent is prohibited.",
    ],
  },
  {
    heading: "Service Availability",
    body: "We do not guarantee uninterrupted availability of the service. The platform is provided on an 'as is' and 'as available' basis. We reserve the right to modify, suspend, or discontinue the service at any time without notice.",
  },
  {
    heading: "Modifications to These Terms",
    body: "We reserve the right to update these Terms and Conditions at any time. The date at the top of this page reflects the most recent revision. Your continued use of the platform following any changes constitutes acceptance of the revised terms.",
  },
  {
    heading: "Governing Law",
    body: "These Terms shall be governed by and construed in accordance with applicable law, without regard to conflict of law principles. Any disputes shall be resolved through good-faith negotiation before any formal proceedings.",
  },
  {
    heading: "Contact",
    body: "For questions about these Terms, contact the developer via LinkedIn at linkedin.com/in/sankalp-indish or via GitHub at github.com/SankalpIndish.",
  },
];

export default function TermsAndConditions() {
  return (
    <div
      className="flex flex-col min-h-[calc(100vh-56px)]"
      style={{ backgroundColor: "var(--bg-primary)", color: "var(--text-primary)" }}
    >
      <main className="flex-1">
        {/* Header */}
        <div
          className="w-full border-b"
          style={{ borderColor: "var(--border-c)", backgroundColor: "var(--bg-secondary)" }}
        >
          <div className="max-w-[1400px] mx-auto px-6 py-12">
            <p
              className="text-[0.5625rem] font-mono uppercase tracking-[0.28em] mb-2"
              style={{ color: "var(--text-muted)" }}
            >
              Legal
            </p>
            <h1 className="text-3xl font-bold tracking-tight mb-1">Terms &amp; Conditions</h1>
            <p
              className="text-[0.625rem] font-mono uppercase tracking-widest"
              style={{ color: "var(--text-muted)" }}
            >
              Last updated: May 2026
            </p>
          </div>
        </div>

        {/* Warning banner */}
        <div
          className="w-full border-b px-6 py-4"
          style={{
            borderColor: "var(--border-c)",
            backgroundColor: "color-mix(in srgb, var(--accent) 8%, transparent)",
          }}
        >
          <div className="max-w-[1400px] mx-auto flex items-start gap-3">
            <span
              className="text-[0.5625rem] font-mono uppercase tracking-widest flex-shrink-0 mt-0.5"
              style={{ color: "var(--accent)" }}
            >
              ⚠ Critical Notice
            </span>
            <p
              className="text-[0.625rem] font-mono"
              style={{ color: "var(--accent)" }}
            >
              This platform is for informational purposes only. Do not use it for life-safety, evacuation, or emergency decisions. Always contact official emergency services in a crisis.
            </p>
          </div>
        </div>

        {/* Body */}
        <div className="max-w-[1400px] mx-auto px-6 py-16 w-full">
          <div className="max-w-3xl">
            <div className="space-y-10">
              {sections.map(({ heading, body }, i) => (
                <div key={heading}>
                  <div className="flex items-start gap-5 mb-4">
                    <span
                      className="text-[0.5625rem] font-mono w-6 flex-shrink-0 mt-1"
                      style={{ color: "var(--text-muted)" }}
                    >
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <h2
                      className="text-base font-bold tracking-tight"
                      style={{ color: "var(--text-primary)" }}
                    >
                      {heading}
                    </h2>
                  </div>

                  <div className="pl-11">
                    {Array.isArray(body) ? (
                      <ul className="space-y-2">
                        {body.map((item, j) => (
                          <li key={j} className="flex gap-3 text-sm leading-relaxed">
                            <span
                              className="flex-shrink-0 mt-1.5 w-1 h-1 rounded-full"
                              style={{ backgroundColor: "var(--accent)" }}
                            />
                            <span
                              style={{
                                color: "var(--text-secondary)",
                                fontFamily: "Georgia, 'Times New Roman', serif",
                              }}
                            >
                              {item}
                            </span>
                          </li>
                        ))}
                      </ul>
                    ) : (
                      <p
                        className="text-sm leading-relaxed"
                        style={{
                          color: heading === "Critical Safety Notice"
                            ? "var(--text-primary)"
                            : "var(--text-secondary)",
                          fontFamily: "Georgia, 'Times New Roman', serif",
                          ...(heading === "Critical Safety Notice" && {
                            borderLeft: "2px solid var(--accent)",
                            paddingLeft: "1rem",
                          }),
                        }}
                      >
                        {body}
                      </p>
                    )}
                  </div>

                  {i < sections.length - 1 && (
                    <div
                      className="mt-10 border-b"
                      style={{ borderColor: "var(--border-c)" }}
                    />
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
